DROP TABLE actuators;

CREATE TABLE IF NOT EXISTS actuators (
  ID_ACTUATOR VARCHAR(30) NOT NULL,
  TIMESTAMP DATETIME NOT NULL,
  STATE BOOLEAN NOT NULL,
  PRIMARY KEY (ID_ACTUATOR,TIMESTAMP));