
CREATE TABLE IF NOT EXISTS profiles (
  ID_PROFILE VARCHAR(30) NOT NULL,
  DAY_OF_WEEK INT NOT NULL,
  START_TIME datetime NOT NULL,
  TEMPERATURE DOUBLE NOT NULL,
  PRIMARY KEY (ID_PROFILE,DAY_OF_WEEK,START_TIME));

CREATE TABLE IF NOT EXISTS air_cond (
  ID_AIR_COND INT NOT NULL,
  MODEL_NAME VARCHAR(30) NOT NULL,
  PRIMARY KEY (ID_AIR_COND));

CREATE TABLE IF NOT EXISTS rooms (
  ID_ROOM VARCHAR(17) NOT NULL,
  ROOM_NAME VARCHAR(30) NOT NULL,
  ID_AIR_COND INT,
  CONN_STATE BOOLEAN,
  ID_PROFILE_WINTER VARCHAR(30),
  ID_PROFILE_SUMMER VARCHAR(30),
  PRIMARY KEY (ID_ROOM),
  FOREIGN KEY (ID_PROFILE_WINTER) REFERENCES profiles (ID_PROFILE),
  FOREIGN KEY (ID_PROFILE_SUMMER) REFERENCES profiles (ID_PROFILE),
  FOREIGN KEY (ID_AIR_COND) REFERENCES air_cond (ID_AIR_COND));


CREATE TABLE IF NOT EXISTS temperatures (
  ID_ROOM VARCHAR(30) NOT NULL,
  TIMESTAMP DATETIME NOT NULL,
  TEMPERATURE DOUBLE NOT NULL,
  PRIMARY KEY (ID_ROOM,TIMESTAMP),
  FOREIGN KEY (ID_ROOM) REFERENCES rooms (ID_ROOM));


CREATE TABLE IF NOT EXISTS actuators (
  ID_ACTUATOR VARCHAR(30) NOT NULL,
  TIMESTAMP DATETIME NOT NULL,
  STATE BOOLEAN NOT NULL,
  PRIMARY KEY (ID_ACTUATOR,TIMESTAMP));


