drop table temperatures;
drop table rooms;
drop table profiles;


CREATE TABLE IF NOT EXISTS profiles (
  ID_PROFILE VARCHAR(30) NOT NULL,
  DAY_OF_WEEK INT NOT NULL,
  START_HOUR int NOT NULL,
  START_MIN int NOT NULL,
  TEMPERATURE DOUBLE NOT NULL,
  PRIMARY KEY (ID_PROFILE,DAY_OF_WEEK,START_HOUR,START_MIN));

CREATE TABLE IF NOT EXISTS rooms (
  ID_ROOM VARCHAR(17) NOT NULL,
  ROOM_NAME VARCHAR(30) NOT NULL,
  ID_AIR_COND INT,
  CONN_STATE BOOLEAN,
  ID_PROFILE_WINTER VARCHAR(30),
  ID_PROFILE_SUMMER VARCHAR(30),
  PRIMARY KEY (ID_ROOM),
  FOREIGN KEY (ID_PROFILE_WINTER) REFERENCES profiles (ID_PROFILE),
  FOREIGN KEY (ID_PROFILE_SUMMER) REFERENCES profiles (ID_PROFILE),
  FOREIGN KEY (ID_AIR_COND) REFERENCES air_cond (ID_AIR_COND));


CREATE TABLE IF NOT EXISTS temperatures (
  ID_ROOM VARCHAR(30) NOT NULL,
  TIMESTAMP DATETIME NOT NULL,
  TEMPERATURE DOUBLE NOT NULL,
  PRIMARY KEY (ID_ROOM,TIMESTAMP),
  FOREIGN KEY (ID_ROOM) REFERENCES rooms (ID_ROOM));


ALTER TABLE rooms
ADD TMODE datetime, ADD MANUAL_TEMP INT, ADD MANUAL_SYSTEM BOOLEAN;


CREATE TABLE IF NOT EXISTS `weekend_mode` (
  `ID` INT NOT NULL,
  `WMODE`BOOLEAN NOT NULL,
  `START_TIME` Datetime,
  `END_TIME` Datetime,
  
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;
